### ISSUE TITLE
Bluemix deployment no longer works

### ISSUE THREAD

**Issue by The-Neo-Noir** [IBM-Blockchain/car-lease-demo#15]
It used to work few days before. But It does not anymore

**Comment by mastersingh24** [comment]
@The-Neo-Noir  - we were having some network issues starting late Sunday but hopefully those issues are resolved now.

**Comment by derjakke** [comment]
Deploy does not work anymore. 

Log:

Installing node modules (package.json)
       npm ERR! Linux 3.19.0-33-generic
       npm ERR! argv "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/staged/app/.npmrc"
       npm ERR! node v4.4.7
       npm ERR! npm  v3.10.6
       npm ERR! No compatible version found: fs@0.0.2
       npm ERR! Valid install targets:
       npm ERR! 0.0.1-security
       npm ERR!
       npm ERR!
       npm ERR! If you need help, you may report this error at:
       npm ERR!     <https://github.com/npm/npm/issues>
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/staged/app/npm-debug.log
-----> Build failed
