### ISSUE TITLE
Deploys, but doesn't work

### ISSUE THREAD

**Issue by kobigurk** [IBM-Blockchain/car-lease-demo#16]
It seems to me that some things have changed with the membership service - it requires a registrar field and a signature field as well, which are not defined in the protobuf structures.
Even after defining them, I then need the enrollKey, which I can't get as I don't have the one-time token that was given when the "admin" user or "WebAppAdmin" user were created.
This causes every registerUser to fail.

What's the easiest way to deploy this to see it running?
Locally was not going smooth too.

**Comment by Jakeeyturner** [comment]
Hi @kobigurk,
Are you still having issues when deploying to Bluemix?

**Comment by kobigurk** [comment]
Since I last tried, it worked great. I'm closing this for now.
