### ISSUE TITLE
Running Create Simple Scenario from Admin Console Time Out

### ISSUE THREAD

**Issue by smcrawford** [IBM-Blockchain/car-lease-demo#23]
Receive the following error:

Creating Scenario

Creating vehicles ✔

 ERROR: Unable to write vehicle ✔

**Comment by Jakeeyturner** [comment]
I believe Bluemix seems to be working fine now, try re-deploying the service and demo.

**Comment by VeitSanner** [comment]
I have the same error message on the UI. While checking the logs I found the following issue during start up:

```
App/0    ENV VARIABLES https://xxx_vp0.us.blockchain.ibm.com 443
App/0    ------------------------------------------ Server Up - http://yyy.mybluemix.net ------------------------------------------
App/0    INFO Startup Locating initial participants
App/0    ENTER Startup INPUT: {}
App/0    ERROR: failed to register, Error: Identity or token does not match.
App/0    Uploaded stats { ok: true }
```

**Comment by Jakeeyturner** [comment]
So it appears that Bluemix service seems to be having some issues still.

VeitSanner, your issue appears to be with the HFC module. When creating users, the registrar needs to be enrolled. The registrar is a user that is provisioned along with the service. Enrolling copies the keystore to a temporary location which is defined in the HFC module. Also, the keystore is locked in the CA so it can't be copied again.

**Comment by VeitSanner** [comment]
@Jakeeyturner the commit 692be9f works for me. I was able to create the full scenario through the admin console.
