### ISSUE TITLE
Deploys to Bluemix, opens up in browser, but doesn't register corresponding chaincode to peers

### ISSUE THREAD

**Issue by nemes1s** [IBM-Blockchain/car-lease-demo#27]
After deployment process, checked out "Newtork" for corresponding Blockchain service, it says: 
**"no chaincode found"**

Looking through logs found this:
**ERR - [36m13:34:46.420 [chaincode] Launch -> DEBU 1b2a9[0m launchAndWaitForRegister failed Error starting container: API error (500): Error: image library/da0f7000-1275-400e-932d-df081589d8cd-vp0-4d62ca88762ba66113aeddb273192ec54533817aee4b575defbb32dbe5facde00dd9a90df8edf4eab3314a9c7ea49bae36e6f7322d3ef49f3360f4350bed9754 not found**

Please help :)

**Comment by 14gracel** [comment]
Hi @nemes1s 

There was an issue with the Blockchain service earlier today which meant chaincode could not be deployed, it should be back up and working. If it is not, give it an hour or so for more networks to be added

Thanks
