### ISSUE TITLE
Error querying chaincode

### ISSUE THREAD

**Issue by nemes1s** [IBM-Blockchain/car-lease-demo#28]
After app deployed and chaincode deployed to peers (checked "Network" tab on corresponding service - hash is there), app fails to create simple scenario.

Error in peer logs:

ERR - [31m13:07:48.501 [rest] processChaincodeInvokeOrQuery -> ERRO 3cf2d[0m Error when querying chaincode: Error:Failed to launch chaincode spec(Timeout expired while starting chaincode 4d62ca88762ba66113aeddb273192ec54533817aee4b575defbb32dbe5facde00dd9a90df8edf4eab3314a9c7ea49bae36e6f7322d3ef49f3360f4350bed9754(networkid:da0f7000-1275-400e-932d-df081589d8cd,peerid:vp0,tx:ab70d55b-ffe6-49ad-9d9c-3185c0b4c792))
ERR - 13:07:48.501 [rest] ProcessChaincode -> INFO 3cf2e[0m REST successfully query chaincode: {"jsonrpc":"2.0","error":{"code":-32003,"message":"Query failure","data":"Error when querying chaincode: Error:Failed to launch chaincode spec(Timeout expired while starting chaincode 4d62ca88762ba66113aeddb273192ec54533817aee4b575defbb32dbe5facde00dd9a90df8edf4eab3314a9c7ea49bae36e6f7322d3ef49f3360f4350bed9754(networkid:da0f7000-1275-400e-932d-df081589d8cd,peerid:vp0,tx:ab70d55b-ffe6-49ad-9d9c-3185c0b4c792))"},"id":123}

**Comment by Jakeeyturner** [comment]
Hi @nemes1s 

Try deleting your 'car_lease_demo' service and application from Bluemix. Then try deploying the car-lease-demo demo again.

In order for the application to work, the 'Network' tab should look something like below.

![service](https://cloud.githubusercontent.com/assets/10009752/18131707/bbeddc0a-6f8b-11e6-8991-4a61f0638aa2.png)

So, the Blockheight must be 2 and there must be a ChainCode ID present. If for any reason there is no ChainCode ID, then it didn't correctly deploy on the peers.

I just tried to create a full scenario and it failed. I then deleted the service and application and re-created them. Then I created a simple scenario and it appeared to work.
I think the Bluemix service is being a bit temperamental at the moment.

**Comment by nemes1s** [comment]
@Jakeeyturner , tried that, new error now:

**ERR - [31m15:53:11.923 [rest] processChaincodeInvokeOrQuery -> ERRO 196cf[0m Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for 2e436d1363bb9f7c00342fa3fe30eff2c303f06ed4a396a06416a5e1e488ead7edd99f337e31fc6692d785bc0d9a30e942f111caccae15e7c34de6c716f0d92a - LedgerError - ResourceNotFound: ledger: resource not found)
ERR - 15:53:11.924 [rest] ProcessChaincode -> INFO 196d0[0m REST successfully query chaincode: {"jsonrpc":"2.0","error":{"code":-32003,"message":"Query failure","data":"Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for 2e436d1363bb9f7c00342fa3fe30eff2c303f06ed4a396a06416a5e1e488ead7edd99f337e31fc6692d785bc0d9a30e942f111caccae15e7c34de6c716f0d92a - LedgerError - ResourceNotFound: ledger: resource not found)"},"id":123}**

**Comment by Jakeeyturner** [comment]
Hi @nemes1s 

There still appears to be some issues with the beta blockchain service, that's why you're receiving the error.
