### ISSUE TITLE
Confusing statement

### ISSUE THREAD

**Issue by just4li** [IBM-Blockchain/car-lease-demo#30]
Lease company transfers the vehicle to a leasee. **The vehicle is not leased instead the application is showing what would happen if the lease were to have come to an end and the leasee activated the purchase option.**

Have no idea what this step #6 try to say.

**Comment by 14gracel** [comment]
Hi @just4li, 

This is saying that a car is only leased once. So instead of the leasing company leasing the car multiple times to different people, it is leased once and the person leading it then owns the car

Does this help?
