### ISSUE TITLE
Deploying to Bluemix Never Works for this demo

### ISSUE THREAD

**Issue by techbm** [IBM-Blockchain/car-lease-demo#33]
Team,Not sure since last 1-2 month demo is not working even after intiating the Deploy on Bluemix as mentioned on : https://github.com/IBM-Blockchain/car-lease-demo/blob/master/Documentation/Installation%20Guide.md#deploying-locally the code is not getting deployed it says deployment failed. May I know by when the issue is going to closed 

Message :

Could not bind to service car_lease_blockchain
Error: Server error, status code: 502, error code: 10001, message: Service broker error: {"description"=>"Error 404 received from broker url https://obc-service-broker-prod.mybluemix.net/v2/service_instances/a0bedf13-970b-442f-8ce8-5717b871eb5c/service_bindings/58a3fbe4-8474-4a2a-bc45-6fcfd213a0b9"}

Finished: FAILED

**Comment by Jakeeyturner** [comment]
Hi @techbm 
I've just checked and the deploy to Bluemix button on the README was pointing to the wrong repo.
This is now fixed and the deployment using that button now works.

Thanks for letting us know of this issue.

**Comment by techbm** [comment]
Just tried and same issue.

FAILED
Could not bind to service car_lease_blockchain
Error: Server error, status code: 502, error code: 10001, message: Service broker error: {"description"=>"Error 404 received from broker url https://obc-service-broker-prod.mybluemix.net/v2/service_instances/a0bedf13-970b-442f-8ce8-5717b871eb5c/service_bindings/333cef86-009b-43e9-8356-09be1d975caf"}

Finished: FAILED

**Comment by Jakeeyturner** [comment]
Hi @techbm 
On Bluemix have you tried deleting the service and application then [redeploying the demo?](https://hub.jazz.net/deploy/index.html?repository=https://github.com/IBM-Blockchain/car-lease-demo.git)

**Comment by techbm** [comment]
I tried in 2 ways. First redeployed by deleting the service and 2nd approach was recreated on a separate instance. In both approach it got failed.

**Comment by Jakeeyturner** [comment]
Hi @techbm 
In order for the demo to work, the service must be created first then the application must be created afterwards. This is all done automatically when pressing the 'Deploy to Bluemix' button on the README file.

Before this can work, there must only be one instance of the service and application in your Bluemix account.
So, any car-lease-demo applications must be deleted as well as any instances of the 'car_lease_blockchain' service before you 'Deploy to Bluemix'.

If this doesn't fix your problems then I'm unsure of what is causing you this issue. Deployment has been working correctly for myself and several others.

Let me know how this goes for you.

**Comment by tayzlor** [comment]
I get this error on initial deployment startup - 

```
ERR ERROR	Startup	OUTPUT: {"message":"Error deploying vehicle chaincode","body":{"jsonrpc":"2.0","error":{"code":-32000,"message":"Registration missing","data":"User not logged in. Use the '/registrar' endpoint to obtain a security token."},"id":12},"error":true}```

**Comment by 14gracel** [comment]
We have updated the demo to work with bluemix with fabric 0.6, please recreate an issue if you have this problem again

**Comment by Akshay-agarwal** [comment]
404 Not Found: Requested route ('car-lease-demo-akshayagarwal-126.mybluemix.net') does not exist.

I am getting this error after i launch app and click on Admin
