### ISSUE TITLE
Deploying to Bluemix Never Works for this demo

### ISSUE THREAD

**Issue by techbm** [IBM-Blockchain/car-lease-demo#34]
This demo is not working. 
Getting the below error. 
Could not bind to service car_lease_blockchain
Error: Server error, status code: 502, error code: 10001, message: Service broker error: {"description"=>"Error 404 received from broker url https://obc-service-broker-prod.mybluemix.net/v2/service_instances/a0bedf13-970b-442f-8ce8-5717b871eb5c/service_bindings/333cef86-009b-43e9-8356-09be1d975caf"}

**Comment by Jakeeyturner** [comment]
Duplicate of #33 #
