### ISSUE TITLE
Unable to run npm install on Win10

### ISSUE THREAD

**Issue by LeonardHarley** [IBM-Blockchain/car-lease-demo#35]
Hi,

I'm trying to get this demo running on a local HL fabric as per the local deployment option in the Installation Guide. Am able to get the membersrvc and peer node started all OK.

However when running npm install in the car-lease-demo directory I get the following error:
`C:\Code\go_code\src\github.com\ibm-blockchain\car-lease-demo\node_modules\x509\build\x509.vcxproj(20,3): error MSB4019:
 The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration
 is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1`

Please advise fix or suggestions - many thanks...

**Comment by mastersingh24** [comment]
Hi - well I could tell you how to get past that error, but then that will just lead to more errors like needing to install openssl, etc.

The x509 package is actually only used in one place.  I'd advise trying to use the "x509.js" package instead.  I believe it's compatible for the x509 package.  You'll want to change https://github.com/IBM-Blockchain/car-lease-demo/blob/master/package.json#L31  (change `x509` to `x509.js` ) and https://github.com/IBM-Blockchain/car-lease-demo/blob/d5d4a4a0a234a5ed81b1ff2ac2f0056c6b54bcd5/Server_Side/blockchain/transactions/CRUD/read.js#L5 ( change `var x509 = require('x509');` to `var x509 = require('x509.js');` )

**Comment by LeonardHarley** [comment]
@mastersingh24 - thanks a mill - that did the trick...
