### ISSUE TITLE
loopback-connector error

### ISSUE THREAD

**Issue by nitesh7sid** [IBM-Blockchain/car-lease-demo#4]
i am trying to add a new user using this library. But the CA code of fabric has changed and it acceps a registrar and its signature.. So i am trying to generate a signature of admin registrar inside the loopback-connector.js file. When i run the function getEnrollmentCertificateFromECA() from the loopback-connector file  to obtain the enrollKey it returns an error "failed to retrieve enrollment certificate error" {[ERROR] code 14, metadata: {internal _repr}}

**Comment by mastersingh24** [comment]
@nitesh7sid  - can you post your code changes here?  we do plan to update things to support the latest version of the fabric / membersvcs soon and will be moving to use the new NodeJS SDK.

**Comment by nitesh7sid** [comment]
OBCCAConnector.prototype.registerUser = function (userRequest, callback) {
//generate enrollment key  of admin registrar 
var registrar_admin={}
.self.getEnrollmentCertificateFromECA(
        { identity: "admin", token: "Xurw3yU9zI0l" },
        function (err, enrollKey, enrollCert, enrollChainKey) {
            if (err)
            {
                console.log('failed to retrieve enrollment certficate:\n',err);
            }
            else
            {
                //debug('enrollKey: ', enrollKey);
                registrar_admin.enrollmentKey = enrollKey;
                console.log('retrieved enrollment certficate');
            }
            
        })

    var registerUserRequest = new this.protos.RegisterUserReq();
    registerUserRequest.setId({ id: userRequest.identity });
    registerUserRequest.setRole(userRequest.role);
    registerUserRequest.setAccount(userRequest.account);
    registerUserRequest.setAffiliation(userRequest.affiliation);
   
  var registrar = new this.protos.Registrar();
   registrar.setId({id: 'admin'});
   registrar.setRoles(['client','peer','validator','auditor']);
   registrar.setDelegateRoles(['client']);
   registerUserRequest.setRegistrar(registrar);

  var buf = registerUserRequest.toBuffer();
    
    //sign the transaction using enrollmentKey
    var EC = elliptic.ec
    var curve = elliptic.curves['p256'];
    var ecdsa = new EC(curve);
    var signKey = ecdsa.keyFromPrivate(registrar_admin.enrollmentKey, 'hex');
    //debug(new Buffer(sha3_384(buf),'hex'));
    var sig = ecdsa.sign(new Buffer(sha3_256(buf), 'hex'), signKey);

    registerUserRequest.setSig(new this.protos.Signature(
        {
            type: this.protos.CryptoType.ECDSA,
            r: new Buffer(sig.r.toString()),
            s: new Buffer(sig.s.toString())
        }
        ));
    
this.ecaaClient.registerUser(registerUserRequest, function (err, token) {
        if (err) {
			console.log("Loopback error:", JSON.stringify(err));
            if (callback) {
                callback(err, null);
            }
        }
        else {

            if (callback) {
                debug(userRequest.identity + ' | ' + token.tok.toString());
                callback(null, { identity: userRequest.identity, token: token.tok.toString() });
            }
        }
    })
};

**Comment by mastersingh24** [comment]
one thing which is missing is that before you sign the `registerUserRequest` you need to set the signature to null:

```
var registerUserRequest = new this.protos.RegisterUserReq();
registerUserRequest.setId({ id: userRequest.identity });
registerUserRequest.setRole(userRequest.role);
registerUserRequest.setAccount(userRequest.account);
registerUserRequest.setAffiliation(userRequest.affiliation);
registerUserRequest.setSig(null);

```

**Comment by nitesh7sid** [comment]
Oh..bt I dnt understand why I can't get enrollmentkey from the function..am I missing something?

**Comment by mastersingh24** [comment]
well if the user is never registered, getEnrollmentKey will fail

**Comment by nitesh7sid** [comment]
the admin is already registered in the membersrvc.yaml

**Comment by mastersingh24** [comment]
oh sorry - I misread and thought you could not get the enrollment info for the user you were trying to register.   How are you using the OBCCAConnector?  You need to pass in the host and port for membersvcs as well as whether or not to use TLS

**Comment by nitesh7sid** [comment]
I am passing the CA IP and port to the datasource settings object...I am passing localhost:50051

**Comment by mastersingh24** [comment]
and did you set secure to true or false?

**Comment by nitesh7sid** [comment]
True...I am actually running my peers using dockers.. So wen k Start my peers I give CORE_SECURITY=true

**Comment by mastersingh24** [comment]
sorry - actually the datasource settings for the OBCCAConnector :+1: 

```
dataSource.settings = {
            host: localhost,
            port: 50051,
            secure: false
        };
```

Are you running membersvcs in a container or as an executable?

**Comment by nitesh7sid** [comment]
i will set it to false and try again..i am running my network using this doc. https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devnet-setup.md

**Comment by nitesh7sid** [comment]
same Error...

**Comment by mastersingh24** [comment]
@nitesh7sid  - so given you are following https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devnet-setup.md , I assume that means you are running this within Vagrant?

**Comment by nitesh7sid** [comment]
No.. I am running outside vagrant..  https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/install.md#building-outside-of-vagrant-

**Comment by mastersingh24** [comment]
okay.  well I can likely get this working, although with the new NodeJS SDK this should be easier.  What's your preference?  Try to get the current connector to work with the new membersrvcs or do you want to try to replace the connector with the new NodeJS SDK?

I actually wrote the OBCCAConnector but it will be going away in favor of the new SDK

**Comment by nitesh7sid** [comment]
i would perefer the new nodejs SDK.
