### ISSUE TITLE
Local Set Up 

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/car-lease-demo#46]
Hey!

I have done local setup for Hyperledger Fabric.
Now I wish to deploy car-lease-demo on my local setup:

I have done the development Environment Setup of Fabric

My Server_Side/configurations/configuration.js file is changed for local setup as follows:
config.networkFile              = /home/vagrant/car-lease-demo/mycreds.json;                             //Put filepath to network data here from bluemix if not using VCAP.  e.g. __dirname+"/../../mycreds.json";
config.networkProtocol  = 'https'                        // The protocol to be used for connecting via rest to the network data peers

//--------------------------------------------------------------------------------------------------------------------
//      Defines the exported values to be used by other fields for connecting to peers or the app. These will be overwritten on app.js being run if Bluemix is being used or Network JSON is defined
//--------------------------------------------------------------------------------------------------------------------
//IP and port configuration
config.api_ip = 'http://172.17.0.3'; //IP of the peer attempting to be connected to. By default this is the first peer in the peers array.

//When using blockchain on bluemix, api_port_external and api_port_internal will be the same
config.api_port_external        = '7051'; //port number used when calling api from outside of the vagrant environment
config.api_port_internal        = '7051'; //port number used when calling api from inside vagrant environment - generally used for chaincode calling out to api
config.api_port_discovery       = '50051' //port number used for HFC

//IP and port configuration for the Certificate Authority. This is used for enrolling WebAppAdmin and creating all the user via HFC. Default values are for running Hyperledger locally.
config.ca_ip    = '172.17.0.1';         //IP of the CA attempting to be connected to
config.ca_port  = '50051';              //Discovery port of the Certificate Authority. Used for HFC

//Settings for the nodeJS application server
config.app_url  = 'http://172.32.68.52';        //Url of the NodeJS Server
config.app_port = 8080;                   

Please help me with local setup deployment for car-lease-demo aaplication

**Comment by 14gracel** [comment]
Please see issue #59
