### ISSUE TITLE
Random crashing on bluemix

### ISSUE THREAD

**Issue by mgzeitouni** [IBM-Blockchain/car-lease-demo#60]
I recently downloaded this demo directly onto bluemix, however in bluemix it is constantly crashing.

I see there was recently an attempt to fix this... has it been resolved? Is there something wrong with my environment or this is a known issue with the demo that is being worked on?

**Comment by 14gracel** [comment]
This issue should be sorted now with the latest commit. Please close the issue if it is

**Comment by mgzeitouni** [comment]
Yep, i deleted and re-deployed the app into bluemix, and now it is working. Thank you!
