### ISSUE TITLE
app server image exits on `docker-compose up`

### ISSUE THREAD

**Issue by evil-shrike** [IBM-Blockchain/car-lease-demo#76]
I run `docker-compose up` on Windows 10 with Docker 1.13.0-rc3, build 4d92237 (w/Linux Containers).

It pulled and built images. But the images with app server exists on starts:
```
carleasedemo_car-lease-demo_1 exited with code 2
```
So only two images carleasedemo_vp0_1 and carleasedemo_membersrvc_1 runnung.

How can I find out what's happening?

**Comment by 14gracel** [comment]
If you run `docker ls -a` you should see the `carleasedemo_car-lease-demo_1` image. Have you made the changes mentioned [here](https://github.com/IBM-Blockchain/car-lease-demo/blob/master/Documentation/Installation%20Guide.md#updating-the-configurations-file)

**Comment by evil-shrike** [comment]
I'm sorry, but what is `docker ls -a`? My docker has no such a command: 

docker: 'ls' is not a docker command.

as for configuration.js, yes, I changed config.*Protocol to:
```
config.networkProtocol = 'http'; 
config.appProtocol = 'http'; 
config.hfcProtocol = 'grpc';
```

**Comment by 14gracel** [comment]
Sorry, that is my fault, I made a typo. I meant to say `docker ps -a`. This lists all of the docker containers that are/were running. If the demo started and quit, it will say 'exited'. You can run `docker logs <id-of-the-docker-container>` to see the car lease demo logs. You will find the id when you run the `docker ps -a` command

**Comment by evil-shrike** [comment]
```
C:\...D\hyperledger\car-lease-demo\Server_Side\configurations>docker logs a3478bc7045b
: not foundocker-startup.sh: 1: ./Scripts/docker-startup.sh:
: not foundocker-startup.sh: 3: ./Scripts/docker-startup.sh:
./Scripts/docker-startup.sh: 5: set: Illegal option -
```

**Comment by evil-shrike** [comment]
I've finally understood what was wrong. It's because on line endings - the repo has no `.gitattributes`, I cloned it onto Windows so with autocrlf=true I got Windows line endings in *.sh files and they failed inside Linux in Docker.
I'd recommend adding `.gitattributes` file into the repo with (at least)
```
* text=auto
*.sh text eol=lf
```

**Comment by bellaj** [comment]
you are right if a user is under windows he should run 

`git config --global core.autocrlf false
`
before to clone the repo
