### ISSUE TITLE
Error deploying to Bluemix

### ISSUE THREAD

**Issue by dexgus** [IBM-Blockchain/car-lease-demo#78]
I'm getting errors when using button "Deploy to Bluemix". I've tried different regions and spaces, but I keep getting the same error:
The application is deployed and the repo are created successfully. However the application never starts. I've read posts with similar errors, but I'm not sure this is the same thing. Here are the error messages:

ERROR Startup OUTPUT: "Failed to enroll registrar with WebAppAdmin 828183e76b"
at /home/vcap/app/node_modules/grpc/src/node/src/client.js:417:17 code: 2, metadata: Metadata { _internal_repr: {} } }
{ Error: Identity or token does not match.
ERROR Startup OUTPUT: {"code":2,"metadata":{"_internal_repr":{}}}
Uploaded stats { ok: true }
events.js:160
at ClientDuplexStream._emitStatusIfDone (/home/vcap/app/node_modules/grpc/src/node/src/client.js:189:19)
throw er; // Unhandled 'error' event
at ClientDuplexStream._readsDone (/home/vcap/app/node_modules/grpc/src/node/src/client.js:158:8)
at readCallback (/home/vcap/app/node_modules/grpc/src/node/src/client.js:217:12)
App instance exited with guid 4f70087a-222d-4540-b50b-b8e1affd008d payload: {"cc_partition"=>"default", "droplet"=>"4f70087a-222d-4540-b50b-b8e1affd008d", "version"=>"f6ff9b7a-54d6-4e7d-9aeb-53749b470a0b", "instance"=>"62bd27fbe5904526b6479702f218200b", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1482256260}

Can someone help figure out what's wrong here?

**Comment by 14gracel** [comment]
Hi @dexgus, do you have any other Blockchain services in bluemix called `car_lease_blockchain`? This tends to be an issue with an instance of the service existing before the demo is deployed

**Comment by dexgus** [comment]
Hi@14gracel, I checked every space in each region, but there wasn't another service called `car_lease_blockchain` anywhere. However I gave it another try, and this time the application started successfully. I suppose the issue was caused by instability in some other service. Anyway, thanks for your help.
