### ISSUE TITLE
Can't deploy using default settings

### ISSUE THREAD

**Issue by NicolasMas** [IBM-Blockchain/car-lease-demo#85]
Hi, trying to build the demo, at the deployment stage (Push to Cloud Foundry 1) it ends up with a failed status. Am new to CF, so I don't really understand what's going on. Below the logs from the build pipeline.

Downloading

 artifacts...DOWNLOAD SUCCESSFUL
Target: https://api.ng.bluemix.net
Creating service instance car_lease_blockchain in org XXXX / space US Space as XXXX.XXX@XXXX.com...
OK
Service car_lease_blockchain already exists
Using manifest file /home/pipeline/f6bf48ba-859e-422a-b554-4fa645bc72de/manifest.yml

Creating app car-lease-demo-XXXXX-1614 in org XXXX / space US Space as XXXX.XXXX@XXXX.com...
OK

Using route car-lease-demo-XXXX-1614.mybluemix.net
Binding car-lease-demo-XXXX-1614.mybluemix.net to car-lease-demo-XXXX-1614...
OK

Uploading car-lease-demo-XXXX-1614...
Uploading app files from: /home/pipeline/f6bf48ba-859e-422a-b554-4fa645bc72de
Uploading 14.7M, 3052 files

                             
Done uploading
OK
Binding service car_lease_blockchain to app car-lease-demo-XXXX-1614 in org Nonya / space US Space as XXXX.XXXX@XXXX.com...
OK

Starting app car-lease-demo-XXXX-1614 in org Nonya / space US Space as XXXX.XXXX@XXXX.com...
Downloading noop-buildpack...
Downloading liberty-for-java...
Downloading dotnet-core...
Downloading sdk-for-nodejs...
Downloading swift_buildpack...
Downloaded sdk-for-nodejs
Downloading go_buildpack...
Downloaded dotnet-core
Downloading java_buildpack...
Downloaded liberty-for-java
Downloading ruby_buildpack...
Downloaded noop-buildpack
Downloading nodejs_buildpack...
Downloaded swift_buildpack
Downloading xpages_buildpack...
Downloaded go_buildpack
Downloading python_buildpack...
Downloaded java_buildpack
Downloading php_buildpack...
Downloaded ruby_buildpack
Downloading staticfile_buildpack...
Downloaded xpages_buildpack
Downloading binary_buildpack...
Downloaded nodejs_buildpack
Downloading swift_buildpack_v2_0_2-20161118-1326...
Downloaded python_buildpack
Downloading liberty-for-java_v3_4_1-20161030-2241...
Downloaded php_buildpack
Downloading sdk-for-nodejs_v3_8-20161006-1211...
Downloaded staticfile_buildpack
Downloading liberty-for-java_v3_5-20161114-1152...
Downloaded binary_buildpack
Downloading dotnet-core_v1_0_1-20161005-1225...
Downloaded liberty-for-java_v3_4_1-20161030-2241
Downloading xpages_buildpack_v1_2_1-20160913-103...
Downloaded swift_buildpack_v2_0_2-20161118-1326
Downloaded liberty-for-java_v3_5-20161114-1152
Downloaded xpages_buildpack_v1_2_1-20160913-103
Creating container
Downloaded sdk-for-nodejs_v3_8-20161006-1211
Downloaded dotnet-core_v1_0_1-20161005-1225
Successfully created container
Downloading app package...
Downloaded app package (29.3M)
Staging...
-----> IBM SDK for Node.js Buildpack v3.9-20161128-1327
       Based on Cloud Foundry Node.js Buildpack v1.5.20
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  ^6.9.1
       engines.npm (package.json):   ^3.10.8
       
       Resolving node version ^6.9.1 via 'node-version-resolver'
       Installing IBM SDK for Node.js (6.9.1) from cache
       Resolving npm version ^3.10.8 via semver.io...
       Downloading and installing npm 3.10.10 (replacing version 3.10.8)...
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Checking and configuring service extensions before installing dependencies
-----> Building dependencies
       Installing node modules (package.json)
       
       > hashtable@2.0.2 install /tmp/app/node_modules/hashtable
       > node-gyp configure build
       
       make: Entering directory `/tmp/app/node_modules/hashtable/build'
       CXX(target) Release/obj.target/native/src/hashtable.o
       SOLINK_MODULE(target) Release/obj.target/native.node
       COPY Release/native.node
       
       > sleep@3.0.1 install /tmp/app/node_modules/sleep
       > node-gyp rebuild
       
       make: Entering directory `/tmp/app/node_modules/sleep/build'
       CXX(target) Release/obj.target/node_sleep/sleep.o
       SOLINK_MODULE(target) Release/obj.target/node_sleep.node
       COPY Release/node_sleep.node
       make: Leaving directory `/tmp/app/node_modules/sleep/build'
       
       > grpc@1.0.0 install /tmp/app/node_modules/grpc
       > node-pre-gyp install --fallback-to-build
       
       [grpc] Success: "/tmp/app/node_modules/grpc/src/node/extension_binary/grpc_node.node" is installed via remote
       
       > x509@0.3.0 install /tmp/app/node_modules/x509
       > node-gyp rebuild
       
       make: Entering directory `/tmp/app/node_modules/x509/build'
       CXX(target) Release/obj.target/x509/src/addon.o
       In file included from ../node_modules/nan/nan.h:194:0,
       from ../include/x509.h:7,
       from ../src/addon.cc:5:
       ../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
       ../node_modules/nan/nan_maybe_43_inl.h:220:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated (declared at /home/vcap/.node-gyp/6.9.1/include/node/v8.h:3031): Cloning is not supported. [-Wdeprecated-declarations]
       return array->CloneElementAt(GetCurrentContext(), index);
       ^
       In file included from ../node_modules/nan/nan_new.h:189:0,
       from ../node_modules/nan/nan.h:200,
       from ../include/x509.h:7,
       from ../src/addon.cc:5:
       ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
       ../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated (declared at /home/vcap/.node-gyp/6.9.1/include/node/v8.h:4007): Pass an isolate [-Wdeprecated-declarations]
       return v8::BooleanObject::New(value).As<v8::BooleanObject>();
       ^
       In file included from ../include/x509.h:7:0,
       from ../src/addon.cc:5:
       ../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
       ../node_modules/nan/nan.h:1969:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated (declared at /home/vcap/.node-gyp/6.9.1/include/node/v8.h:2750): Use maybe version [-Wdeprecated-declarations]
       , attribute);
       ^
       CXX(target) Release/obj.target/x509/src/x509.o
       In file included from ../node_modules/nan/nan.h:194:0,
       from ../include/x509.h:7,
       ../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
       ../node_modules/nan/nan_maybe_43_inl.h:220:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated (declared at /home/vcap/.node-gyp/6.9.1/include/node/v8.h:3031): Cloning is not supported. [-Wdeprecated-declarations]
       return array->CloneElementAt(GetCurrentContext(), index);
       ^
       In file included from ../node_modules/nan/nan_new.h:189:0,
       from ../node_modules/nan/nan.h:200,
       from ../include/x509.h:7,
       from ../src/x509.cc:2:
       ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
       ../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated (declared at /home/vcap/.node-gyp/6.9.1/include/node/v8.h:4007): Pass an isolate [-Wdeprecated-declarations]
       return v8::BooleanObject::New(value).As<v8::BooleanObject>();
       ^
       In file included from ../include/x509.h:7:0,
       from ../src/x509.cc:2:
       ../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
       ../node_modules/nan/nan.h:1969:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated (declared at /home/vcap/.node-gyp/6.9.1/include/node/v8.h:2750): Use maybe version [-Wdeprecated-declarations]
       , attribute);
       ^
       ../src/x509.cc: In function ‘v8::Local<v8::Value> try_parse(const string&)’:
       ../src/x509.cc:357:38: warning: value computed is not used [-Wunused-value]
       ^
       ../src/x509.cc: In function ‘v8::Local<v8::Value> parse_date(ASN1_TIME*)’:
       ../src/x509.cc:420:60: warning: ‘v8::Local<v8::Value> v8::Object::CallAsConstructor(int, v8::Local<v8::Value>*)’ is deprecated (declared at /home/vcap/.node-gyp/6.9.1/include/node/v8.h:2996): Use maybe version [-Wdeprecated-declarations]
       return scope.Escape(DateObject->CallAsConstructor(1, args));
       ^
       SOLINK_MODULE(target) Release/obj.target/x509.node
       COPY Release/x509.node
       make: Leaving directory `/tmp/app/node_modules/x509/build'
       Car-Lease-Demo@0.7.3 /tmp/app
       ├─┬ body-parser@1.0.2
       │ ├── qs@0.6.6
       │ ├─┬ raw-body@1.1.7
       │ │ ├── bytes@1.0.0
       │ │ └── string_decoder@0.10.31
       │ └─┬ type-is@1.1.0
       │   └── mime@1.2.11
       ├─┬ cf-deployment-tracker-client@0.1.2
       │ ├─┬ cwd@0.10.0
       │ │ ├─┬ find-pkg@0.1.2
       │ │ │ └─┬ find-file-up@0.1.3
       │ │ │   └─┬ resolve-dir@0.1.1
       │ │ │     ├─┬ expand-tilde@1.2.2
       │ │ │     │ └── os-homedir@1.0.2
       │ │ │     └─┬ global-modules@0.2.3
       │ │ │       ├─┬ global-prefix@0.1.5
       │ │ │       │ ├─┬ homedir-polyfill@1.0.1
       │ │ │       │ │ └── parse-passwd@1.0.0
       │ │ │       │ ├── ini@1.3.4
       │ │ │       │ └─┬ which@1.2.12
       │ │ │       └── is-windows@0.2.0
       │ │ └── fs-exists-sync@0.1.0
       │ └─┬ restler@3.3.0
       │   ├── iconv-lite@0.2.11
       │   ├── qs@1.2.0
       │   ├─┬ xml2js@0.4.0
       │   │ ├── sax@0.5.8
       │   │ └── xmlbuilder@8.2.2
       │   └── yaml@0.2.3
       ├─┬ cookie-parser@1.0.1
       │ ├── cookie@0.1.0
       │ └── cookie-signature@1.0.3
       ├─┬ cors@2.5.3
       │ └── vary@1.1.0
       ├─┬ express@4.14.0
       │ ├─┬ accepts@1.3.3
       │ │ └── negotiator@0.6.1
       │ ├── array-flatten@1.1.1
       │ ├── content-disposition@0.5.1
       │ ├── content-type@1.0.2
       │ ├── cookie@0.3.1
       │ ├── cookie-signature@1.0.6
       │ ├─┬ debug@2.2.0
       │ │ └── ms@0.7.1
       │ ├── depd@1.1.0
       │ ├── encodeurl@1.0.1
       │ ├── escape-html@1.0.3
       │ ├── etag@1.7.0
       │ ├─┬ finalhandler@0.5.0
       │ │ ├── statuses@1.3.1
       │ │ └── unpipe@1.0.0
       │ ├── fresh@0.3.0
       │ ├── merge-descriptors@1.0.1
       │ ├── methods@1.1.2
       │ ├─┬ on-finished@2.3.0
       │ │ └── ee-first@1.1.1
       │ ├── parseurl@1.3.1
       │ ├── path-to-regexp@0.1.7
       │ ├─┬ proxy-addr@1.1.2
       │ │ ├── forwarded@0.1.0
       │ │ └── ipaddr.js@1.1.1
       │ ├── qs@6.2.0
       │ ├── range-parser@1.2.0
       │ ├─┬ send@0.14.1
       │ │ ├── destroy@1.0.4
       │ │ ├─┬ http-errors@1.5.1
       │ │ │ └── setprototypeof@1.0.2
       │ │ └── mime@1.3.4
       │ ├── serve-static@1.11.1
       │ ├─┬ type-is@1.6.14
       │ │ └── media-typer@0.3.0
       │ └── utils-merge@1.0.0
       ├─┬ express-session@1.14.2
       │ ├── cookie@0.3.1
       │ ├── cookie-signature@1.0.6
       │ ├── crc@3.4.1
       │ ├── on-headers@1.0.1
       │ └─┬ uid-safe@2.1.3
       │   ├── base64-url@1.3.3
       │   └── random-bytes@1.0.0
       ├── fs@0.0.1-security
       ├─┬ hfc@0.6.5
       │ ├── aes-js@1.0.0
       │ ├── asn1@0.2.3  (git+https://github.com/mcavage/node-asn1.git#2c2a19e285a609adfca36a0114bb5b86cf4ac61b)
       │ ├── asn1js@1.2.12
       │ ├── crypto@0.0.3
       │ ├─┬ elliptic@6.3.2
       │ │ ├── brorand@1.0.6
       │ │ ├── hash.js@1.0.3
       │ │ └── inherits@2.0.3
       │ ├─┬ es6-set@0.1.4
       │ │ ├── d@0.1.1
       │ │ ├── es5-ext@0.10.12
       │ │ ├── es6-iterator@2.0.0
       │ │ ├── es6-symbol@3.1.0
       │ │ └── event-emitter@0.3.4
       │ ├── events@1.1.1
       │ ├── fs@0.0.2
       │ ├─┬ grpc@1.0.0
       │ │ ├── lodash@3.10.1
       │ │ ├── nan@2.5.0
       │ │ ├─┬ node-pre-gyp@0.6.29
       │ │ │ ├─┬ mkdirp@0.5.1
       │ │ │ │ └── minimist@0.0.8
       │ │ │ ├─┬ nopt@3.0.6
       │ │ │ │ └── abbrev@1.0.9
       │ │ │ ├─┬ npmlog@3.1.2
       │ │ │ │ ├─┬ are-we-there-yet@1.1.2
       │ │ │ │ │ ├── delegates@1.0.0
       │ │ │ │ │ └─┬ readable-stream@2.1.5
       │ │ │ │ │   ├── buffer-shims@1.0.0
       │ │ │ │ │   ├── core-util-is@1.0.2
       │ │ │ │ │   ├── inherits@2.0.1
       │ │ │ │ │   ├── isarray@1.0.0
       │ │ │ │ │   ├── process-nextick-args@1.0.7
       │ │ │ │ │   ├── string_decoder@0.10.31
       │ │ │ │ │   └── util-deprecate@1.0.2
       │ │ │ │ ├── console-control-strings@1.1.0
       │ │ │ │ ├─┬ gauge@2.6.0
       │ │ │ │ │ ├── aproba@1.0.4
       │ │ │ │ │ ├── has-color@0.1.7
       │ │ │ │ │ ├── has-unicode@2.0.1
       │ │ │ │ │ ├── object-assign@4.1.0
       │ │ │ │ │ ├── signal-exit@3.0.0
       │ │ │ │ │ ├─┬ string-width@1.0.2
       │ │ │ │ │ │ ├─┬ code-point-at@1.0.0
       │ │ │ │ │ │ │ └── number-is-nan@1.0.0
       │ │ │ │ │ │ └─┬ is-fullwidth-code-point@1.0.0
       │ │ │ │ │ │   └── number-is-nan@1.0.0
       │ │ │ │ │ ├─┬ strip-ansi@3.0.1
       │ │ │ │ │ │ └── ansi-regex@2.0.0
       │ │ │ │ │ └── wide-align@1.1.0
       │ │ │ │ └── set-blocking@2.0.0
       │ │ │ ├─┬ rc@1.1.6
       │ │ │ │ ├── deep-extend@0.4.1
       │ │ │ │ ├── ini@1.3.4
       │ │ │ │ ├── minimist@1.2.0
       │ │ │ │ └── strip-json-comments@1.0.4
       │ │ │ ├─┬ request@2.74.0
       │ │ │ │ ├── aws-sign2@0.6.0
       │ │ │ │ ├── aws4@1.4.1
       │ │ │ │ ├─┬ bl@1.1.2
       │ │ │ │ │ └─┬ readable-stream@2.0.6
       │ │ │ │ │   ├── core-util-is@1.0.2
       │ │ │ │ │   ├── inherits@2.0.1
       │ │ │ │ │   ├── isarray@1.0.0
       │ │ │ │ │   ├── process-nextick-args@1.0.7
       │ │ │ │ │   ├── string_decoder@0.10.31
       │ │ │ │ │   └── util-deprecate@1.0.2
       │ │ │ │ ├── caseless@0.11.0
       │ │ │ │ ├─┬ combined-stream@1.0.5
       │ │ │ │ │ └── delayed-stream@1.0.0
       │ │ │ │ ├── extend@3.0.0
       │ │ │ │ ├── forever-agent@0.6.1
       │ │ │ │ ├─┬ form-data@1.0.0-rc4
       │ │ │ │ │ └── async@1.5.2
       │ │ │ │ ├─┬ har-validator@2.0.6
       │ │ │ │ │ ├─┬ chalk@1.1.3
       │ │ │ │ │ │ ├── ansi-styles@2.2.1
       │ │ │ │ │ │ ├── escape-string-regexp@1.0.5
       │ │ │ │ │ │ ├─┬ has-ansi@2.0.0
       │ │ │ │ │ │ │ └── ansi-regex@2.0.0
       │ │ │ │ │ │ ├─┬ strip-ansi@3.0.1
       │ │ │ │ │ │ │ └── ansi-regex@2.0.0
       │ │ │ │ │ │ └── supports-color@2.0.0
       │ │ │ │ │ ├─┬ commander@2.9.0
       │ │ │ │ │ │ └── graceful-readlink@1.0.1
       │ │ │ │ │ ├─┬ is-my-json-valid@2.13.1
       │ │ │ │ │ │ ├── generate-function@2.0.0
       │ │ │ │ │ │ ├─┬ generate-object-property@1.2.0
       │ │ │ │ │ │ │ └── is-property@1.0.2
       │ │ │ │ │ │ ├── jsonpointer@2.0.0
       │ │ │ │ │ │ └── xtend@4.0.1
       │ │ │ │ │ └─┬ pinkie-promise@2.0.1
       │ │ │ │ │   └── pinkie@2.0.4
       │ │ │ │ ├─┬ hawk@3.1.3
       │ │ │ │ │ ├── boom@2.10.1
       │ │ │ │ │ ├── cryptiles@2.0.5
       │ │ │ │ │ ├── hoek@2.16.3
       │ │ │ │ │ └── sntp@1.0.9
       │ │ │ │ ├─┬ http-signature@1.1.1
       │ │ │ │ │ ├── assert-plus@0.2.0
       │ │ │ │ │ ├─┬ jsprim@1.3.0
       │ │ │ │ │ │ ├── extsprintf@1.0.2
       │ │ │ │ │ │ ├── json-schema@0.2.2
       │ │ │ │ │ │ └── verror@1.3.6
       │ │ │ │ │ └─┬ sshpk@1.9.2
       │ │ │ │ │   ├── asn1@0.2.3
       │ │ │ │ │   ├── assert-plus@1.0.0
       │ │ │ │ │   ├── dashdash@1.14.0
       │ │ │ │ │   ├── ecc-jsbn@0.1.1
       │ │ │ │ │   ├── getpass@0.1.6
       │ │ │ │ │   ├── jodid25519@1.0.2
       │ │ │ │ │   ├── jsbn@0.1.0
       │ │ │ │ │   └── tweetnacl@0.13.3
       │ │ │ │ ├── is-typedarray@1.0.0
       │ │ │ │ ├── isstream@0.1.2
       │ │ │ │ ├── json-stringify-safe@5.0.1
       │ │ │ │ ├─┬ mime-types@2.1.11
       │ │ │ │ │ └── mime-db@1.23.0
       │ │ │ │ ├── node-uuid@1.4.7
       │ │ │ │ ├── oauth-sign@0.8.2
       │ │ │ │ ├── qs@6.2.1
       │ │ │ │ ├── stringstream@0.0.5
       │ │ │ │ ├── tough-cookie@2.3.1
       │ │ │ │ └── tunnel-agent@0.4.3
       │ │ │ ├─┬ rimraf@2.5.4
       │ │ │ │ └─┬ glob@7.0.5
       │ │ │ │   ├── fs.realpath@1.0.0
       │ │ │ │   ├─┬ inflight@1.0.5
       │ │ │ │   │ └── wrappy@1.0.2
       │ │ │ │   ├── inherits@2.0.1
       │ │ │ │   ├─┬ minimatch@3.0.3
       │ │ │ │   │ └─┬ brace-expansion@1.1.6
       │ │ │ │   │   ├── balanced-match@0.4.2
       │ │ │ │   ├─┬ once@1.3.3
       │ │ │ │   │ └── wrappy@1.0.2
       │ │ │ │   │   └── concat-map@0.0.1
       │ │ │ │   └── path-is-absolute@1.0.0
       │ │ │ ├── semver@5.2.0
       │ │ │ ├─┬ tar@2.2.1
       │ │ │ │ ├── block-stream@0.0.9
       │ │ │ │ ├─┬ fstream@1.0.10
       │ │ │ │ │ └── graceful-fs@4.1.5
       │ │ │ │ └── inherits@2.0.1
       │ │ │ └─┬ tar-pack@3.1.4
       │ │ │   ├─┬ debug@2.2.0
       │ │ │   │ └── ms@0.7.1
       │ │ │   ├─┬ fstream@1.0.10
       │ │ │   │ ├── graceful-fs@4.1.5
       │ │ │   │ └── inherits@2.0.1
       │ │ │   ├─┬ fstream-ignore@1.0.5
       │ │ │   │ ├── inherits@2.0.1
       │ │ │   │ └─┬ minimatch@3.0.3
       │ │ │   │   └─┬ brace-expansion@1.1.6
       │ │ │   │     ├── balanced-match@0.4.2
       │ │ │   │     └── concat-map@0.0.1
       │ │ │   ├─┬ once@1.3.3
       │ │ │   │ └── wrappy@1.0.2
       │ │ │   ├─┬ readable-stream@2.1.5
       │ │ │   │ ├── buffer-shims@1.0.0
       │ │ │   │ ├── core-util-is@1.0.2
       │ │ │   │ ├── inherits@2.0.1
       │ │ │   │ ├── isarray@1.0.0
       │ │ │   │ ├── process-nextick-args@1.0.7
       │ │ │   │ ├── string_decoder@0.10.31
       │ │ │   │ └── util-deprecate@1.0.2
       │ │ │   └── uid-number@0.0.6
       │ │ └─┬ protobufjs@4.1.3
       │ │   ├─┬ ascli@1.0.1
       │ │   │ ├── colour@0.7.1
       │ │   │ └── optjs@3.2.2
       │ │   │ ├── bufferview@1.0.1
       │ │   │ └── long@2.4.0
       │ │   ├─┬ glob@5.0.15
       │ │   │ └── inflight@1.0.6
       │ │   └─┬ yargs@3.32.0
       │ │     ├── camelcase@2.1.1
       │ │     ├─┬ cliui@3.2.0
       │ │     │ └── wrap-ansi@2.1.0
       │ │     ├── decamelize@1.2.0
       │ │     ├─┬ os-locale@1.4.0
       │ │     │ └─┬ lcid@1.0.0
       │ │     │   └── invert-kv@1.0.0
       │ │     ├─┬ string-width@1.0.2
       │ │     │ ├── code-point-at@1.1.0
       │ │     │ └─┬ is-fullwidth-code-point@1.0.0
       │ │     │   └── number-is-nan@1.0.1
       │ │     ├── window-size@0.1.4
       │ │     └── y18n@3.2.1
       │ ├─┬ hashtable@2.0.2
       │ │ └── nan@2.5.0
       │ ├── js-sha3@0.5.7
       │ ├── json-stringify-safe@5.0.1
       │ ├── jssha@2.2.0
       │ ├── node-uuid@1.4.7
       │ ├─┬ node.extend@1.1.6
       │ │ └── is@3.2.0
       │ ├── pkijs@1.3.33
       │ ├── sjcl@1.0.3
       │ ├── sjcl-codec@0.1.1
       │ ├── sleep@3.0.1
       │ ├─┬ tar-fs@1.15.0
       │ │ ├─┬ mkdirp@0.5.1
       │ │ │ └── minimist@0.0.8
       │ │ ├─┬ pump@1.0.2
       │ │ │ ├─┬ end-of-stream@1.1.0
       │ │ │ │ └── once@1.3.3
       │ │ │ └─┬ once@1.4.0
       │ │ │   └── wrappy@1.0.2
       │ │ └─┬ tar-stream@1.5.2
       │ │   ├── bl@1.2.0
       │ │   ├─┬ readable-stream@2.2.2
       │ │   │ ├── buffer-shims@1.0.0
       │ │   │ ├── core-util-is@1.0.2
       │ │   │ ├── isarray@1.0.0
       │ │   │ ├── process-nextick-args@1.0.7
       │ │   │ └── util-deprecate@1.0.2
       │ │   └── xtend@4.0.1
       │ ├─┬ typedoc@0.4.5
       │ │ ├─┬ fs-extra@0.30.0
       │ │ │ ├── graceful-fs@4.1.11
       │ │ │ ├── jsonfile@2.4.0
       │ │ │ ├── klaw@1.3.1
       │ │ │ ├── path-is-absolute@1.0.1
       │ │ │ └─┬ rimraf@2.5.4
       │ │ │   └── glob@7.1.1
       │ │ ├─┬ handlebars@4.0.5
       │ │ │ ├── async@1.5.2
       │ │ │ ├─┬ optimist@0.6.1
       │ │ │ │ └── wordwrap@0.0.3
       │ │ │ ├─┬ source-map@0.4.4
       │ │ │ │ └── amdefine@1.0.1
       │ │ │ └─┬ uglify-js@2.7.5
       │ │ │   ├── async@0.2.10
       │ │ │   ├── source-map@0.5.6
       │ │ │   ├── uglify-to-browserify@1.0.2
       │ │ │   └─┬ yargs@3.10.0
       │ │ │     ├── camelcase@1.2.1
       │ │ │     ├─┬ cliui@2.1.0
       │ │ │     │ ├─┬ center-align@0.1.3
       │ │ │     │ │ ├─┬ align-text@0.1.4
       │ │ │     │ │ │ ├─┬ kind-of@3.1.0
       │ │ │     │ │ │ │ └── is-buffer@1.1.4
       │ │ │     │ │ │ ├── longest@1.0.1
       │ │ │     │ │ │ └── repeat-string@1.6.1
       │ │ │     │ │ └── lazy-cache@1.0.4
       │ │ │     │ ├── right-align@0.1.3
       │ │ │     │ └── wordwrap@0.0.2
       │ │ │     └── window-size@0.1.0
       │ │ ├── highlight.js@9.9.0
       │ │ ├── lodash@4.17.4
       │ │ ├── marked@0.3.6
       │ │ ├─┬ minimatch@3.0.3
       │ │ │   ├── balanced-match@0.4.2
       │ │ │   └── concat-map@0.0.1
       │ │ ├── progress@1.1.8
       │ │ ├─┬ shelljs@0.7.5
       │ │ │ ├─┬ glob@7.1.1
       │ │ │ │ └── fs.realpath@1.0.0
       │ │ │ ├── interpret@1.0.1
       │ │ │ └─┬ rechoir@0.6.2
       │ │ │   └── resolve@1.2.0
       │ │ └── typedoc-default-themes@0.4.1
       │ ├── typescript@1.8.10
       │ ├─┬ url@0.11.0
       │ │ ├── punycode@1.3.2
       │ │ └── querystring@0.2.0
       │ ├─┬ util@0.10.3
       │ │ └── inherits@2.0.1
       │ └── uuidv4@0.3.1
       ├─┬ request@2.79.0
       │ ├── aws-sign2@0.6.0
       │ ├── aws4@1.5.0
       │ ├── caseless@0.11.0
       │ ├─┬ combined-stream@1.0.5
       │ │ └── delayed-stream@1.0.0
       │ ├── extend@3.0.0
       │ ├── forever-agent@0.6.1
       │ ├─┬ form-data@2.1.2
       │ │ └── asynckit@0.4.0
       │ ├─┬ har-validator@2.0.6
       │ │ ├─┬ chalk@1.1.3
       │ │ │ ├── ansi-styles@2.2.1
       │ │ │ ├── escape-string-regexp@1.0.5
       │ │ │ ├─┬ has-ansi@2.0.0
       │ │ │ │ └── ansi-regex@2.0.0
       │ │ │ ├── strip-ansi@3.0.1
       │ │ │ └── supports-color@2.0.0
       │ │ ├─┬ commander@2.9.0
       │ │ │ └── graceful-readlink@1.0.1
       │ │ ├─┬ is-my-json-valid@2.15.0
       │ │ │ ├── generate-function@2.0.0
       │ │ │ ├─┬ generate-object-property@1.2.0
       │ │ │ │ └── is-property@1.0.2
       │ │ │ └── jsonpointer@4.0.1
       │ │ └─┬ pinkie-promise@2.0.1
       │ │   └── pinkie@2.0.4
       │ ├─┬ hawk@3.1.3
       │ │ ├── boom@2.10.1
       │ │ ├── cryptiles@2.0.5
       │ │ ├── hoek@2.16.3
       │ │ └── sntp@1.0.9
       │ ├─┬ http-signature@1.1.1
       │ │ ├── assert-plus@0.2.0
       │ │ ├─┬ jsprim@1.3.1
       │ │ │ ├── extsprintf@1.0.2
       │ │ │ ├── json-schema@0.2.3
       │ │ │ └── verror@1.3.6
       │ │ └─┬ sshpk@1.10.1
       │ │   ├── assert-plus@1.0.0
       │ │   ├── bcrypt-pbkdf@1.0.0
       │ │   ├─┬ dashdash@1.14.1
       │ │   │ └── assert-plus@1.0.0
       │ │   ├── ecc-jsbn@0.1.1
       │ │   ├─┬ getpass@0.1.6
       │ │   │ └── assert-plus@1.0.0
       │ │   ├── jodid25519@1.0.2
       │ │   ├── jsbn@0.1.0
       │ │   └── tweetnacl@0.14.5
       │ ├── is-typedarray@1.0.0
       │ ├── isstream@0.1.2
       │ ├─┬ mime-types@2.1.13
       │ │ └── mime-db@1.25.0
       │ ├── oauth-sign@0.8.2
       │ ├── qs@6.3.0
       │ ├── stringstream@0.0.5
       │ ├─┬ tough-cookie@2.3.2
       │ ├── tunnel-agent@0.4.3
       │ └── uuid@3.0.1
       └─┬ x509@0.3.0
       └── nan@2.2.0
       
-----> Checking and configuring service extensions after installing dependencies
-----> Installing App Management
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
       ├── body-parser@1.0.2
       ├── cf-deployment-tracker-client@0.1.2
       ├── cookie-parser@1.0.1
       ├── cors@2.5.3
       ├── express@4.14.0
       ├── express-session@1.14.2
       ├── fs@0.0.1-security
       ├── hfc@0.6.5
       ├── request@2.79.0
       └── x509@0.3.0
       
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (24.2M)
Uploaded droplet (69.6M)
Uploading complete
Destroying container
Successfully destroyed container

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 crashed
FAILED
Error restarting application: Start unsuccessful

TIP: use 'cf logs car-lease-demo-XXXX-1614 --recent' for more information

Finished: FAILED

**Comment by Fraydel** [comment]
Same problem here, worked perfectly fine last week.

**Comment by Jakeeyturner** [comment]
Hi @NicolasMas,
We've made a few changes so hopefully you shouldn't have a problem anymore.

Let me know how it goes,
Thanks.

**Comment by NicolasMas** [comment]
Deploys now. Tks!

**Comment by pheneghan1** [comment]
Hi
Was a new issue introduced? I have the same issue today 7/14/2017.
Thanks
