### ISSUE TITLE
[SOLVED] 502 Bad Gateway: Registered endpoint failed to handle the request.

### ISSUE THREAD

**Issue by NicolasMas** [IBM-Blockchain/car-lease-demo#86]
When loading he URL ` https://car-lease-demo-XXXXXX-XXX.mybluemix.net/` (I rebuilt everything with the latest master branch, no issues at the build+deployement stage from the jazz log).

**Comment by NicolasMas** [comment]
Need to increase the "GB MEMORY PER INSTANCE". The default value is too low.

**Comment by Sangeethavijay** [comment]
It worked. Thank you.
