### ISSUE TITLE
Cannot deploy on Ubutu locally

### ISSUE THREAD

**Issue by alexjipark** [IBM-Blockchain/car-lease-demo#88]
Hello, I've been trying to deploy this demo on Ubuntu locally but I failed..

I suppose it's to do with "hastable" module.. 
Here's logs after I run './start.sh'.. Someone help me out, plz?

=========================== 
ubuntu@ip-172-31-23-140:~/cuppa/hyperledger_demo/car-lease-demo/Scripts$ ./start.sh 

# Grab the Car Lease Demo directory.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )";
 cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd 
 dirname "${BASH_SOURCE[0]}" 

# If the keyValStore exits, remove it
if [ -f $DIR/keyValStore ]
then
    rm -r $DIR/keyValStore;
fi

# Tag the latest version of fabric-baseimage
docker pull hyperledger/fabric-baseimage:x86_64-0.1.0
x86_64-0.1.0: Pulling from hyperledger/fabric-baseimage
Digest: sha256:ac6a2784cfd028ae62f5688f4436f95d7a60eeacd8506eb303c9c6335328c388
Status: Image is up to date for hyperledger/fabric-baseimage:x86_64-0.1.0
docker tag hyperledger/fabric-baseimage:x86_64-0.1.0 hyperledger/fabric-baseimage:latest

# Clean up old docker containers
docker-compose -f $DIR/docker-compose.yml kill;
docker-compose -f $DIR/docker-compose.yml down;
Removing network carleasedemo_default
WARNING: Network carleasedemo_default not found.
docker-compose -f $DIR/docker-compose.yml build;
Building membersrvc
Step 1 : FROM hyperledger/fabric-membersrvc:latest
 ---> b3654d32e4f9
Step 2 : COPY membersrvc.yaml ./membersrvc
 ---> Using cache
 ---> eff1ae954f58
Successfully built eff1ae954f58
vp0 uses an image, skipping
Building car-lease-demo
Step 1 : FROM node:argon
 ---> 8a7d28500d95
Step 2 : RUN apt-get -y update && apt-get -y install netcat
 ---> Using cache
 ---> 3013e4ea8dc6
Step 3 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> d52babd60d43
Step 4 : WORKDIR /usr/src/app
 ---> Using cache
 ---> a97ed6483d5e
Step 5 : RUN npm install -g npm
 ---> Using cache
 ---> 51a2e6f6d484
Step 6 : COPY package.json /usr/src/app/
 ---> 67a2ee79c484
Removing intermediate container 2813d63c7480
Step 7 : RUN npm install --quiet
 ---> Running in afd981a06a29
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated gulp-minify-css@1.2.1: Please use gulp-clean-css
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> hashtable@2.0.2 install /usr/src/app/node_modules/hashtable
> node-gyp configure build

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v4.7.1-headers.tar.gz local checksum 65662b3bb57577e7a8fa254522befa688620a786d2648061900050ade00d33f5 not match remote 7eb5c43e61eb70115792ead0a1b4b66d4afe5f2a040214e7c2753cbd09113093
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:266:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:309:13)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:923:12)
gyp ERR! stack     at nextTickCallbackWith2Args (node.js:458:9)
gyp ERR! stack     at process._tickCallback (node.js:372:17)
gyp ERR! System Linux 3.13.0-105-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/src/app/node_modules/hashtable
gyp ERR! node -v v4.7.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
Car-Lease-Demo@0.7.3 /usr/src/app
+-- body-parser@1.0.2 
| +-- qs@0.6.6 
| +-- raw-body@1.1.7 
| | +-- bytes@1.0.0 
| | `-- string_decoder@0.10.31 
| `-- type-is@1.1.0 
|   `-- mime@1.2.11 
+-- cf-deployment-tracker-client@0.1.2 
| +-- cwd@0.10.0 
| | +-- find-pkg@0.1.2 
| | | `-- find-file-up@0.1.3 
| | |   `-- resolve-dir@0.1.1 
| | |     +-- expand-tilde@1.2.2 
| | |     `-- global-modules@0.2.3 
| | |       +-- global-prefix@0.1.5 
| | |       | +-- homedir-polyfill@1.0.1 
| | |       | | `-- parse-passwd@1.0.0 
| | |       | `-- ini@1.3.4 
| | |       `-- is-windows@0.2.0 
| | `-- fs-exists-sync@0.1.0 
| `-- restler@3.3.0 
|   +-- iconv-lite@0.2.11 
|   +-- qs@1.2.0 
|   +-- xml2js@0.4.0 
|   | +-- sax@0.5.8 
|   | `-- xmlbuilder@8.2.2 
|   `-- yaml@0.2.3 
+-- cookie-parser@1.0.1 
| +-- cookie@0.1.0 
| `-- cookie-signature@1.0.3 
+-- cors@2.5.3 
| `-- vary@1.1.0 
+-- express@4.14.0 
| +-- accepts@1.3.3 
| | `-- negotiator@0.6.1 
| +-- array-flatten@1.1.1 
| +-- content-disposition@0.5.1 
| +-- content-type@1.0.2 
| +-- cookie@0.3.1 
| +-- cookie-signature@1.0.6 
| +-- debug@2.2.0 
| | `-- ms@0.7.1 
| +-- depd@1.1.0 
| +-- encodeurl@1.0.1 
| +-- escape-html@1.0.3 
| +-- etag@1.7.0 
| +-- finalhandler@0.5.0 
| | +-- statuses@1.3.1 
| | `-- unpipe@1.0.0 
| +-- fresh@0.3.0 
| +-- merge-descriptors@1.0.1 
| +-- methods@1.1.2 
| +-- on-finished@2.3.0 
| | `-- ee-first@1.1.1 
| +-- parseurl@1.3.1 
| +-- path-to-regexp@0.1.7 
| +-- proxy-addr@1.1.2 
| | +-- forwarded@0.1.0 
| | `-- ipaddr.js@1.1.1 
| +-- qs@6.2.0 
| +-- range-parser@1.2.0 
| +-- send@0.14.1 
| | +-- destroy@1.0.4 
| | +-- http-errors@1.5.1 
| | | `-- setprototypeof@1.0.2 
| | `-- mime@1.3.4 
| +-- serve-static@1.11.1 
| +-- type-is@1.6.14 
| | `-- media-typer@0.3.0 
| `-- utils-merge@1.0.0 
+-- express-session@1.14.2 
| +-- cookie@0.3.1 
| +-- cookie-signature@1.0.6 
| +-- crc@3.4.1 
| +-- on-headers@1.0.1 
| `-- uid-safe@2.1.3 
|   +-- base64-url@1.3.3 
|   `-- random-bytes@1.0.0 
+-- fs@0.0.1-security 
+-- gulp-concat@2.6.1 
| +-- concat-with-sourcemaps@1.0.4 
| | `-- source-map@0.5.6 
| +-- through2@2.0.3 
| | `-- xtend@4.0.1 
| `-- vinyl@2.0.1 
|   +-- clone@1.0.2 
|   +-- clone-buffer@1.0.0 
|   +-- clone-stats@1.0.0 
|   +-- cloneable-readable@1.0.0 
|   +-- is-stream@1.1.0 
|   +-- remove-trailing-separator@1.0.1 
|   `-- replace-ext@1.0.0 
+-- gulp-minify-css@1.2.1 
| +-- clean-css@3.4.23 
| | `-- commander@2.8.1 
| |   `-- graceful-readlink@1.0.1 
| +-- object-assign@4.1.0 
| +-- readable-stream@2.2.2 
| | +-- buffer-shims@1.0.0 
| | +-- core-util-is@1.0.2 
| | +-- inherits@2.0.3 
| | +-- isarray@1.0.0 
| | +-- process-nextick-args@1.0.7 
| | `-- util-deprecate@1.0.2 
| +-- vinyl-bufferstream@1.0.1 
| | `-- bufferstreams@1.0.1 
| |   `-- readable-stream@1.1.14 
| |     `-- isarray@0.0.1 
| `-- vinyl-sourcemaps-apply@0.1.4 
|   `-- source-map@0.1.43 
+-- gulp-rename@1.2.2 
+-- gulp-sass@2.3.2 
| +-- lodash.clonedeep@4.5.0 
| +-- node-sass@3.13.1 
| | +-- async-foreach@0.1.3 
| | +-- cross-spawn@3.0.1 
| | | +-- lru-cache@4.0.2 
| | | | +-- pseudomap@1.0.2 
| | | | `-- yallist@2.0.0 
| | | `-- which@1.2.12 
| | |   `-- isexe@1.1.2 
| | +-- gaze@1.1.2 
| | | `-- globule@1.1.0 
| | |   +-- glob@7.1.1 
| | |   `-- lodash@4.16.6 
| | +-- get-stdin@4.0.1 
| | +-- glob@7.1.1 
| | | +-- fs.realpath@1.0.0 
| | | +-- inflight@1.0.6 
| | | | `-- wrappy@1.0.2 
| | | `-- once@1.4.0 
| | +-- in-publish@2.0.0 
| | +-- lodash.assign@4.2.0 
| | +-- meow@3.7.0 
| | | +-- camelcase-keys@2.1.0 
| | | | `-- camelcase@2.1.1 
| | | +-- decamelize@1.2.0 
| | | +-- loud-rejection@1.6.0 
| | | | +-- currently-unhandled@0.4.1 
| | | | | `-- array-find-index@1.0.2 
| | | | `-- signal-exit@3.0.2 
| | | +-- map-obj@1.0.1 
| | | +-- minimist@1.2.0 
| | | +-- normalize-package-data@2.3.5 
| | | | +-- hosted-git-info@2.1.5 
| | | | +-- is-builtin-module@1.0.0 
| | | | | `-- builtin-modules@1.1.1 
| | | | `-- validate-npm-package-license@3.0.1 
| | | |   +-- spdx-correct@1.0.2 
| | | |   | `-- spdx-license-ids@1.2.2 
| | | |   `-- spdx-expression-parse@1.0.4 
| | | +-- read-pkg-up@1.0.1 
| | | | +-- find-up@1.1.2 
| | | | | `-- path-exists@2.1.0 
| | | | `-- read-pkg@1.1.0 
| | | |   +-- load-json-file@1.1.0 
| | | |   | `-- parse-json@2.2.0 
| | | |   |   `-- error-ex@1.3.0 
| | | |   |     `-- is-arrayish@0.2.1 
| | | |   `-- path-type@1.1.0 
| | | +-- redent@1.0.0 
| | | | +-- indent-string@2.1.0 
| | | | | `-- repeating@2.0.1 
| | | | |   `-- is-finite@1.0.2 
| | | | `-- strip-indent@1.0.1 
| | | `-- trim-newlines@1.0.0 
| | +-- mkdirp@0.5.1 
| | | `-- minimist@0.0.8 
| | +-- nan@2.5.0 
| | +-- node-gyp@3.4.0 
| | | +-- fstream@1.0.10 
| | | +-- glob@7.1.1 
| | | +-- minimatch@3.0.3 
| | | | `-- brace-expansion@1.1.6 
| | | |   +-- balanced-match@0.4.2 
| | | |   `-- concat-map@0.0.1 
| | | +-- nopt@3.0.6 
| | | | `-- abbrev@1.0.9 
| | | +-- npmlog@3.1.2 
| | | | `-- gauge@2.6.0 
| | | |   `-- has-color@0.1.7 
| | | +-- osenv@0.1.4 
| | | | +-- os-homedir@1.0.2 
| | | | `-- os-tmpdir@1.0.2 
| | | +-- path-array@1.0.1 
| | | | `-- array-index@1.0.0 
| | | |   `-- es6-symbol@3.1.0 
| | | |     +-- d@0.1.1 
| | | |     `-- es5-ext@0.10.12 
| | | |       `-- es6-iterator@2.0.0 
| | | +-- rimraf@2.5.4 
| | | | `-- glob@7.1.1 
| | | +-- semver@5.3.0 
| | | `-- tar@2.2.1 
| | |   `-- block-stream@0.0.9 
| | +-- npmlog@4.0.2 
| | | +-- are-we-there-yet@1.1.2 
| | | | `-- delegates@1.0.0 
| | | +-- console-control-strings@1.1.0 
| | | +-- gauge@2.7.2 
| | | | +-- aproba@1.0.4 
| | | | +-- has-unicode@2.0.1 
| | | | +-- string-width@1.0.2 
| | | | | +-- code-point-at@1.1.0 
| | | | | `-- is-fullwidth-code-point@1.0.0 
| | | | |   `-- number-is-nan@1.0.1 
| | | | +-- supports-color@0.2.0 
| | | | `-- wide-align@1.1.0 
| | | `-- set-blocking@2.0.0 
| | `-- sass-graph@2.1.2 
| |   +-- glob@7.1.1 
| |   +-- lodash@4.17.4 
| |   `-- yargs@4.8.1 
| |     +-- cliui@3.2.0 
| |     | `-- wrap-ansi@2.1.0 
| |     +-- get-caller-file@1.0.2 
| |     +-- os-locale@1.4.0 
| |     | `-- lcid@1.0.0 
| |     |   `-- invert-kv@1.0.0 
| |     +-- require-directory@2.1.1 
| |     +-- require-main-filename@1.0.1 
| |     +-- which-module@1.0.0 
| |     +-- window-size@0.2.0 
| |     +-- y18n@3.2.1 
| |     `-- yargs-parser@2.4.1 
| |       `-- camelcase@3.0.0 
| `-- vinyl-sourcemaps-apply@0.2.1 
|   `-- source-map@0.5.6 
+-- gulp-sourcemaps@1.9.1 
| +-- acorn@4.0.4 
| +-- convert-source-map@1.3.0 
| +-- css@2.2.1 
| | +-- source-map@0.1.43 
| | +-- source-map-resolve@0.3.1 
| | | +-- atob@1.1.3 
| | | +-- resolve-url@0.2.1 
| | | `-- source-map-url@0.3.0 
| | `-- urix@0.1.0 
| +-- debug-fabulous@0.0.4 
| | `-- lazy-debug-legacy@0.0.1 
| +-- detect-newline@2.1.0 
| +-- graceful-fs@4.1.11 
| +-- source-map@0.4.4 
| | `-- amdefine@1.0.1 
| +-- strip-bom@2.0.0 
| | `-- is-utf8@0.2.1 
| `-- vinyl@1.2.0 
|   +-- clone-stats@0.0.1 
|   `-- replace-ext@0.0.1 
+-- gulp-uglify@1.5.4 
| +-- deap@1.0.0 
| +-- fancy-log@1.3.0 
| | `-- time-stamp@1.0.1 
| +-- isobject@2.1.0 
| +-- uglify-js@2.6.4 
| | +-- async@0.2.10 
| | +-- source-map@0.5.6 
| | +-- uglify-to-browserify@1.0.2 
| | `-- yargs@3.10.0 
| |   +-- camelcase@1.2.1 
| |   +-- cliui@2.1.0 
| |   | +-- center-align@0.1.3 
| |   | | +-- align-text@0.1.4 
| |   | | | +-- longest@1.0.1 
| |   | | | `-- repeat-string@1.6.1 
| |   | | `-- lazy-cache@1.0.4 
| |   | +-- right-align@0.1.3 
| |   | `-- wordwrap@0.0.2 
| |   `-- window-size@0.1.0 
| +-- uglify-save-license@0.4.1 
| `-- vinyl-sourcemaps-apply@0.2.1 
+-- gulp-util@3.0.8 
| +-- array-differ@1.0.0 
| +-- array-uniq@1.0.3 
| +-- beeper@1.1.1 
| +-- chalk@1.1.3 
| | +-- ansi-styles@2.2.1 
| | +-- escape-string-regexp@1.0.5 
| | +-- has-ansi@2.0.0 
| | | `-- ansi-regex@2.0.0 
| | +-- strip-ansi@3.0.1 
| | `-- supports-color@2.0.0 
| +-- dateformat@2.0.0 
| +-- gulplog@1.0.0 
| | `-- glogg@1.0.0 
| +-- has-gulplog@0.1.0 
| | `-- sparkles@1.0.0 
| +-- lodash._reescape@3.0.0 
| +-- lodash._reevaluate@3.0.0 
| +-- lodash._reinterpolate@3.0.0 
| +-- lodash.template@3.6.2 
| | +-- lodash._basecopy@3.0.1 
| | +-- lodash._basetostring@3.0.1 
| | +-- lodash._basevalues@3.0.0 
| | +-- lodash._isiterateecall@3.0.9 
| | +-- lodash.escape@3.2.0 
| | | `-- lodash._root@3.0.1 
| | +-- lodash.keys@3.1.2 
| | | +-- lodash._getnative@3.9.1 
| | | +-- lodash.isarguments@3.1.0 
| | | `-- lodash.isarray@3.0.4 
| | +-- lodash.restparam@3.6.1 
| | `-- lodash.templatesettings@3.1.1 
| +-- minimist@1.2.0 
| +-- multipipe@0.1.2 
| | `-- duplexer2@0.0.2 
| |   `-- readable-stream@1.1.14 
| |     `-- isarray@0.0.1 
| +-- object-assign@3.0.0 
| +-- replace-ext@0.0.1 
| `-- vinyl@0.5.3 
|   `-- clone-stats@0.0.1 
+-- gulp-watch@4.3.11 
| +-- anymatch@1.3.0 
| | +-- arrify@1.0.1 
| | `-- micromatch@2.3.11 
| |   +-- arr-diff@2.0.0 
| |   | `-- arr-flatten@1.0.1 
| |   +-- array-unique@0.2.1 
| |   +-- braces@1.8.5 
| |   | +-- expand-range@1.8.2 
| |   | | `-- fill-range@2.2.3 
| |   | |   +-- is-number@2.1.0 
| |   | |   `-- randomatic@1.1.6 
| |   | +-- preserve@0.2.0 
| |   | `-- repeat-element@1.1.2 
| |   +-- expand-brackets@0.1.5 
| |   | `-- is-posix-bracket@0.1.1 
| |   +-- extglob@0.3.2 
| |   +-- filename-regex@2.0.0 
| |   +-- is-extglob@1.0.0 
| |   +-- kind-of@3.1.0 
| |   | `-- is-buffer@1.1.4 
| |   +-- normalize-path@2.0.1 
| |   +-- object.omit@2.0.1 
| |   | +-- for-own@0.1.4 
| |   | | `-- for-in@0.1.6 
| |   | `-- is-extendable@0.1.1 
| |   +-- parse-glob@3.0.4 
| |   | +-- glob-base@0.3.0 
| |   | | `-- glob-parent@2.0.0 
| |   | `-- is-dotfile@1.0.2 
| |   `-- regex-cache@0.4.3 
| |     +-- is-equal-shallow@0.1.3 
| |     `-- is-primitive@2.0.0 
| +-- chokidar@1.6.1 
| | +-- async-each@1.0.1 
| | +-- glob-parent@2.0.0 
| | +-- is-binary-path@1.0.1 
| | | `-- binary-extensions@1.8.0 
| | +-- is-glob@2.0.1 
| | `-- readdirp@2.1.0 
| |   `-- set-immediate-shim@1.0.1 
| +-- glob-parent@3.1.0 
| | +-- is-glob@3.1.0 
| | | `-- is-extglob@2.1.1 
| | `-- path-dirname@1.0.2 
| +-- path-is-absolute@1.0.1 
| +-- slash@1.0.0 
| +-- vinyl@1.2.0 
| | +-- clone-stats@0.0.1 
| | `-- replace-ext@0.0.1 
| `-- vinyl-file@2.0.0 
|   +-- pify@2.3.0 
|   +-- pinkie-promise@2.0.1 
|   | `-- pinkie@2.0.4 
|   +-- strip-bom-stream@2.0.0 
|   | `-- first-chunk-stream@2.0.0 
|   `-- vinyl@1.2.0 
|     +-- clone-stats@0.0.1 
|     `-- replace-ext@0.0.1 
+-- request@2.79.0 
| +-- aws-sign2@0.6.0 
| +-- aws4@1.5.0 
| +-- caseless@0.11.0 
| +-- combined-stream@1.0.5 
| | `-- delayed-stream@1.0.0 
| +-- extend@3.0.0 
| +-- forever-agent@0.6.1 
| +-- form-data@2.1.2 
| | `-- asynckit@0.4.0 
| +-- har-validator@2.0.6 
| | +-- commander@2.9.0 
| | `-- is-my-json-valid@2.15.0 
| |   +-- generate-function@2.0.0 
| |   +-- generate-object-property@1.2.0 
| |   | `-- is-property@1.0.2 
| |   `-- jsonpointer@4.0.1 
| +-- hawk@3.1.3 
| | +-- boom@2.10.1 
| | +-- cryptiles@2.0.5 
| | +-- hoek@2.16.3 
| | `-- sntp@1.0.9 
| +-- http-signature@1.1.1 
| | +-- assert-plus@0.2.0 
| | +-- jsprim@1.3.1 
| | | +-- extsprintf@1.0.2 
| | | +-- json-schema@0.2.3 
| | | `-- verror@1.3.6 
| | `-- sshpk@1.10.1 
| |   +-- asn1@0.2.3  (git+https://github.com/mcavage/node-asn1.git#2c2a19e285a609adfca36a0114bb5b86cf4ac61b)
| |   +-- assert-plus@1.0.0 
| |   +-- bcrypt-pbkdf@1.0.0 
| |   +-- dashdash@1.14.1 
| |   | `-- assert-plus@1.0.0 
| |   +-- ecc-jsbn@0.1.1 
| |   +-- getpass@0.1.6 
| |   | `-- assert-plus@1.0.0 
| |   +-- jodid25519@1.0.2 
| |   +-- jsbn@0.1.0 
| |   `-- tweetnacl@0.14.5 
| +-- is-typedarray@1.0.0 
| +-- isstream@0.1.2 
| +-- json-stringify-safe@5.0.1 
| +-- mime-types@2.1.13 
| | `-- mime-db@1.25.0 
| +-- oauth-sign@0.8.2 
| +-- qs@6.3.0 
| +-- stringstream@0.0.5 
| +-- tough-cookie@2.3.2 
| | `-- punycode@1.4.1 
| +-- tunnel-agent@0.4.3 
| `-- uuid@3.0.1 
`-- x509@0.3.0 
  `-- nan@2.2.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.13.0-105-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--quiet"
npm ERR! node v4.7.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@2.0.2 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hashtable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hashtable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hashtable
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
ERROR: Service 'car-lease-demo' failed to build: The command '/bin/sh -c npm install --quiet' returned a non-zero code: 1
ubuntu@ip-172-31-23-140:~/cuppa/hyperledger_demo/car-lease-demo/Scripts$

**Comment by kesavannb** [comment]
Hi , 
I'm also facing the same issue , 
can you explain how did you fixed (npm-uuid 1.4.8 )  the issue.
