### ISSUE TITLE
start.sh issue - calls apt-get on RHEL

### ISSUE THREAD

**Issue by xuqingsz** [IBM-Blockchain/car-lease-demo#98]
Hi,

I installed all the dependencies on RHEL 6.8 made sure everything runs just fine.
Could not get start.sh to finish, hence executed it line by line. While it was executing 
% docker-compose -f docker-compose.yml build
it runs
% apt-get -y update && apt-get -y install netcat

I had netcat installed (yum install nc) but docker-compose went ahead and tried to install anyways. Looks like it doesn't know its on a RHEL, and went ahead and called apt-get. 

Am i missing some setup somewhere, to tell docker-compose, or the yml file that I am in RHEL?

Thanks.

**Comment by mrshah-at-ibm** [comment]
it looks like the `apt get` is running inside an intermediate ubuntu or debian container. So, it should be okay!

**Comment by xuqingsz** [comment]
Thanks. You are right. The problem ended up being not having set proxy http in the Dockerfile correctly.

**Comment by xuqingsz** [comment]
Hi @mrshah-at-ibm,

Could you please point to me the piece of code/settings that defines Linux Distro of intermediate container? I happen to have the need now to run an intermediate RHEL container on an Debian system. 

Also to expand from here, would the underlying architecture (x86, ppc, etc) be visible for that container, or apps in that container?

Thanks

**Comment by mrshah-at-ibm** [comment]
if you look at the Dockerfile, it says `FROM debian:latests` or `FROM ubuntu:latest`. This defines the base image on which your image is built.

yes, the underlying architecture will be visible. You will have to use the ppc, etc base images instead of generic x86 ubuntu images if you are using a different architecture.

Hope it helps.

**Comment by xuqingsz** [comment]
Thanks a lot.
